### ISSUE TITLE
Multiple File Submissions

### ISSUE THREAD

**Issue by ProbieK** [PaulSec/API-malwr.com#6]
Hey! Great script!

One thing that I'd like to do is be able to submit an entire folder of files.

Something like being able to submit a '~/tmp/*' in the file path argument.
Then be able to retrieve all of the links to the reports for each file.

A coworker and I are looking at editing it ourselves. But neither of us are proficient in Python.

**Comment by PaulSec** [comment]
I see, that's pretty much do-able. 
Let me create a new branch in the next couple of days and I will work on this. 

I will update the thread so you can give it a shot and see if that works! 

Glad you like it, cheers!

**Comment by nstr10** [comment]
Essentially, all you would need to do to accomplish this would be something like

`````` python
filelist = [f for f in listdir("/path/to/folder")]
for item in filelist:
    api_authenticated = MalwrAPI()
    result = api_authenticated.submit_sample(filepath = "/path/to/folder/"+item)
    # maybe do things with result```
``````

**Comment by PaulSec** [comment]
Hi guys, 

Sorry for the late reploy. 

It's done and pushed. 

``` python
res = api_unauthenticated.submit_folder('/tmp/malware/')
print res
```

Output is: 

```
[{'analysis_link': '/analysis/NzM4NjhiNzUNDMxMzhiM2FmZDA5MTQ3MDMxNjE/', 'file': '/tmp/malware/test.txt', 'md5': 'd1bf8fc6af9166875136587ad697a719'}, {'analysis_link': '/submission/status/NzUzNzg5NDFmM2MyNDcyhZjNkYjIxYmRkOTU3YTE/', 'file': '/tmp/malware/dlksldksdlk.txt', 'md5': 'f285b089031740f866f3d5676311e3a7'}]
```

I will work on a multi-threaded version if this method is too slow.

**Comment by ProbieK** [comment]
We'll take a look. Thank you!
